### ISSUE TITLE
remove fontawesome dependency

### ISSUE THREAD

**Issue by OnkelMato** [awesome-inc/NZazu#105]
fontawesome is the icon provider for nzazu and cannot be replaced easily. a redesign would make sense to extract an icon provider and implement a provider for fontawesome and mahapps.

**Comment by mkoertgen** [comment]
Agreed. Icon Support should be optional, Not mandatory.
What parts so actually depend in fontawesome.sharp?

**Comment by wgnf** [comment]
Possibly *only* the `GeoLocationBox`?
