### ISSUE TITLE
support dotnet core

### ISSUE THREAD

**Issue by OnkelMato** [awesome-inc/NZazu#106]
current dotnet core is not supported. it would be useful to support wpf on dotnet core.

**Comment by mkoertgen** [comment]
The Main Advantage of core ist Cross Platform support, easier builds due to core cli and simpler, convention based Projects.

Since NZazu has heavily bought into WPF, we are basically pinned to Windows only.

What other use cases would promote core?

**Comment by wgnf** [comment]
- Using the new .csproj format would make managing projects and the corresponding NuGet-Packages easier. 
- The Core CLR is great
- Using .NET Core is not only about Cross-Platform, its also about not being left behind by new features and all that stuff that comes with .NET Core and (soon) .NET Version 5 (.NET Framework will not receive any features in the future)
- New Applications generally won't use .NET Framework anymore, but .NET Core. When these new Applications want to use NZazu it won't be possible.
- Not supporting .NET Core (and .NET Framework) will render NZazu obsolete sooner or later.

Migrating over to the new .csproj Format and with that having the ability to support both .NET Framework AND .NET Core isn't generally that difficult (as long as all used Packages are supporting both aswell). 
I don't see any reason to not do it.

**Comment by mkoertgen** [comment]
No objection either. 

Note that the current version of FontAwesome.Sharp is already migrated to .NET Core 3.1 cf #105
