### ISSUE TITLE
allow multiple behaviors to attach separate functionality to a field

### ISSUE THREAD

**Issue by ghost** [awesome-inc/NZazu#29]
e.g. a "Open URL on Strg+Enter" behavior can be combined with "Correct spelling on Strg+Alt+P"

**Comment by ghost** [comment]
it makes sense to move the sample for opening links to the NZazu project.

**Comment by htochenhagen** [comment]
Multiple behaviors can be defined since version 0.6.22. As an example, the example class "BehaviorSample" has been extended accordingly.

**Comment by mkoertgen** [comment]
@htochenhagen @ThomasMentzel @janbo485 Please note, that since this introduces a new feature this should have been resulting in version 0.7.0, not 0.6.22 (patch).

Also, there should be a corresponding PR for this without bypassing code review/quality gates.
