### ISSUE TITLE
fix behavior test

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/NZazu#33]
complete test coverage by finishing behavior test, cf.: https://github.com/ThomasMentzel/NZazu/blob/master/NZazu/Fields/NZazuFieldFactory_Should.cs#L127

It seems we forgot that when merging the pull request.

**Comment by ghost** [comment]
it is fixed. the test was renamed to ensure the field factory does not attach. in the original version, the test was only moved to another fixture.
