### ISSUE TITLE
RtfTextBox for xceed control shows FormatException on update

### ISSUE THREAD

**Issue by ghost** [awesome-inc/NZazu#72]
The RTF TextBox throws a lot of FormatExceptions, every time you hit a key. After debugging and googling I found out that this is a Windows/.NET issue (and not worth fixing :( ).

http://wpftoolkit.codeplex.com/workitem/19857

https://social.msdn.microsoft.com/Forums/vstudio/en-US/8b2c7bbe-961f-4dc7-8057-4180c2a7aeeb/textrangesave-throws-a-formatexception-when-saving-rtf?forum=wpf

Usually the exceptions were catched but this slows down the system/application.

**Comment by ghost** [comment]
It might be a solution to update the formdata not after a key hit, but after "lost focus" or any other event which does not accur that often.

**Comment by mkoertgen** [comment]
I think it maybe possible to change the binding by overriding `XceedRichTextField.DecorateBinding()`

https://github.com/awesome-inc/NZazu/blob/4eff64203e5ea428ccee859b4d222c4cf658ed1e/NZazu.Xceed/XceedRichTextField.cs
