### ISSUE TITLE
add a location field

### ISSUE THREAD

**Issue by ghost** [awesome-inc/NZazu#88]
Add a location field to NZazu. The field should provide functionality to

* use current location
* open location in geo tool
* support differnt geo formats (at least overridable)

Provide an extensible way to change the geo tool or location provider.

**Comment by OnkelMato** [comment]
fixed in the latest version of NZazu. [Location Field Test](https://github.com/awesome-inc/NZazu/blob/0784570da4e1738dd44e6d2e01a7d5e6770d370d/NZazu/Fields/NZazuFieldFactory_Should.cs#L54url)
