### ISSUE TITLE
Caching Problem with "datatables" - data gets copied

### ISSUE THREAD

**Issue by wgnf** [awesome-inc/NZazu#93]
When using a field of type "datatable" within a template you're able to set the default values of each column with the help of the section "Values", e.g.:
```json 
"Values": {
    "table_locatings": "{\"table_locatings_icon__1\":null,\"table_locatings_time__1\":null,\"table_locatings_lat__1\":null,\"table_locatings_lon__1\":null,\"table_locatings_bearing__1\":null,\"table_locatings_maj__1\":null,\"table_locatings_min__1\":null}"
  }
```
When one is not assigning any default value but is opening the **same** template as before **again** the data that was in the datatable before, gets copied to the new instance. In some circumstances this can be problematic (and overall its clearly an unwanted behavior).

**Example:**
- Editor is working with some sort of form, filling in table rows with maybe important or confidential data
- Editor remembers something that he forgot, so he saves the current form and opens a new form (with the same underlying template) to have a placeholder for the next task that has to be done
- The data from the datatable from before gets copied into the new datatable, but the editor doesn't notice and saves the data anyway.

With some sort of automations in place this could lead to unwanted behavior pretty fast!

**Possbile fixes (imo):**
1. Don't initialize a generated table from type "datatable" with an empty row
2. Delete all data before creating the tabe from type "datatable"

If something is unclear, feel free to ask!

**Comment by mkoertgen** [comment]
Since i was not involved in the design of the data tables feature i would suggest to bring @ThomasLey or @janbo485 to the table
