### ISSUE TITLE
Testing-Framework dependencies in Package

### ISSUE THREAD

**Issue by wgnf** [awesome-inc/NZazu#98]
We're using NZazu in our Product and wanted to update to the newest Version asap. It seems like, that there was an update to the Testing-Frameworks in the meantime, so we had to update those aswell, which resulted in a lot of braking tests because of braking changes in FluentAssertions, NSubstitute etc.
As you can imagine the update was not as "asap" as we wished.

In my opinion a NuGet-Package should not "publish" any dependencies that are not necessarily needed for the Package to work. Testing-Framework-Dependencies are one of them! Those should be in a separate Testing-Project or marked as "development-dependency". 

This enables the consumer to be free to chose it's own Testing-Environment even if the used Package is using something different itself. 
The upsides of this, and downsides of the current situation are obvious in my opinion, but i could with some examples if necessary.

**Comment by mkoertgen** [comment]
@mwagenfuehr Marking the dependencies as dev-dependency is the right way to go.

**Comment by wgnf** [comment]
Created a PR see #99

**Comment by wgnf** [comment]
I guess this can be closed since the PR was merged and closed
